### ISSUE TITLE
Download Fails .. Log Attached

### ISSUE THREAD

**Issue by Adeshwar03** [HritwikSinghal/Clipboard-saavn-song-downloader#6]
Waiting for url from clipboard....
got url:  https://www.jiosaavn.com/s/playlist/577bfd5954de823fedf7acef5d7373be/Hidden_Hindi_Tunes/sIsdQWUuXOruCJW60TJk1Q__
[ERROR] : 2022-01-12 01:47:38,814 : root : (clipboard-saavn-song-downloader.py).start(100) : Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\Clipboard-saavn-song-downloader-master\clipboard-saavn-song-downloader.py", line 97, in start
    my_downloader.run()
  File "C:\Users\xxx\Downloads\Clipboard-saavn-song-downloader-master\src\saavn_downloader.py", line 101, in run
    songs_json: dict = saavn_API.API().fetch_details(url=self.url)
  File "C:\Users\xxx\Downloads\Clipboard-saavn-song-downloader-master\src\tools\saavn_API.py", line 133, in fetch_details
    payload: dict = self._payloads[url_type]
KeyError: 's'

**Comment by HritwikSinghal** [comment]
Hi, thanks for the logs. Where did you find this playlist? and where can i find more of these?

**Comment by Adeshwar03** [comment]
Found it on Pinterest.
https://in.pinterest.com/Barryvsh/jiosaavn-playlist-links/

Has a nice collection

**Comment by HritwikSinghal** [comment]
Hi, i have pushed temporary fix for the issue while i am investigating a permanent fix. Now the program will show you the url's of the songs in that playlist so you need to copy those URL's to a file and run the program with '--file <file-path>' flag to download them.
